In [2]:
import numpy as np

Create a 3D array (2×3×4) filled with 7s.


In [3]:
print(np.full((2,3,4),7))

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


Generate an array of numbers from 50 to 100 with a step of 5.


In [4]:
arr = np.arange(50,101,5)
arr

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100])

Create an identity matrix of size 4.


In [5]:
print(np.identity(4, dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Generate a linearly spaced array between 0 and 1 with 11 points.


In [6]:
print(np.linspace(0,1,11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Replace all odd numbers in an array (1–20) with -1.


In [7]:
arr = np.arange(1,21)
arr[arr % 2 !=0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20]


Reverse the rows of a 3×3 matrix.


In [8]:
arr = np.arange(1,10).reshape(3,3)
print(arr[::-1, :])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


Reverse the cols of a 3×3 matrix.


In [9]:
print(arr[:, ::-1])

[[3 2 1]
 [6 5 4]
 [9 8 7]]


Swap the first and last rows of a 4×4 matrix.


In [10]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
arr[[0,-1]] = arr[[-1,0]]
print(arr)

[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


Create an array of shape (3×3×3) with values 0–26.


In [12]:
arr = np.arange(0,27).reshape(3,3,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Find the index of all elements greater than 50 in a random array of size 15 (1–100).


In [15]:
np.random.seed(0)

arr = np.random.randint(1,100,15)
arr


array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59],
      dtype=int32)

In [20]:
ind = np.where(arr > 50)
print(ind)

(array([ 2,  3,  4,  6,  9, 10, 11, 12, 14]),)


Reshape numbers 1–24 into a 4×6 matrix and extract the 2nd row.


In [22]:
arr1 = np.arange(1,25).reshape(4,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [23]:
arr1[1]

array([ 7,  8,  9, 10, 11, 12])

Stack a 1D array (1–5) into 5 rows (using tile or repeat).


In [33]:
arr2 = np.arange(1,6)
np.tile(arr2, (5,1))

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [30]:
np.repeat([arr2], 5,axis=0)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

Convert a 5×5 matrix into upper-triangular form.


In [34]:
arr3 = np.arange(1,26).reshape(5,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
np.triu(arr3)

array([[ 1,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10],
       [ 0,  0, 13, 14, 15],
       [ 0,  0,  0, 19, 20],
       [ 0,  0,  0,  0, 25]])

Rotate a 3×3 matrix by 90 degrees using transpose and slicing.


In [38]:
rotate = np.arange(1,10).reshape(3,3)
rotated = np.transpose(rotate)[::-1]
rotated

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

Concatenate three arrays [1,2], [3,4], [5,6] into one.


In [44]:
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])
concated = np.concat((a,b,c))
concated

array([1, 2, 3, 4, 5, 6])

Horizontally stack an array [1,2,3] with itself three times.


In [56]:
arr = np.array([1,2,3])
np.hstack([arr,arr,arr])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Split numbers 1–30 into 3 arrays of equal size.


In [58]:
np.split(np.arange(1,31), indices_or_sections=3)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])]