In [1]:
import numpy as np

In [2]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [3]:
np.arange(10,31,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [5]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [6]:
np.linspace(-2,2,9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [12]:
a = np.arange(5,16)
np.where(a>10, 0, a)

array([ 5,  6,  7,  8,  9, 10,  0,  0,  0,  0,  0])

In [23]:
a = np.random.randint(10,100,(4,4))
a

array([[83, 80, 29, 46],
       [74, 13, 84, 20],
       [90, 43, 89, 92],
       [54, 62, 39, 35]], dtype=int32)

In [33]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
a[:, ::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [24]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
a[:, [0,-1]] = a[:,[-1,0]]


In [31]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [43]:
arr = np.random.randint(0,101,20)
np.where(arr<25)[0]

array([ 0,  2, 13])

In [49]:
arr = np.arange(1,25).reshape(6,4)
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [48]:
arr[:,3]

array([ 4,  8, 12, 16, 20, 24])

In [54]:
arr = np.array([2,4,6])
arr

array([2, 4, 6])

In [57]:
np.tile(arr, (4,1))

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [58]:
np.repeat([arr], 4, axis=0)

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [59]:
arr = np.arange(1,17).reshape(4,4)
np.tril(arr)

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

In [62]:
rotate = arr[::-1, ::-1]

In [63]:
rotate

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [66]:
a1 = np.array([10,20,30])
a2 = np.array([40,50])

np.concat((a1,a2))

array([10, 20, 30, 40, 50])

In [77]:
arr = np.arange(1,65).reshape(8,8)
topr = arr[:4, :4]
topl = arr[:4, 4:]
botr = arr[4:, :4]
botl = arr[4:, 4:]

print(topr)
print()
print(topl)
print()
print(botr)
print()
print(botl)

[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]
 [25 26 27 28]]

[[ 5  6  7  8]
 [13 14 15 16]
 [21 22 23 24]
 [29 30 31 32]]

[[33 34 35 36]
 [41 42 43 44]
 [49 50 51 52]
 [57 58 59 60]]

[[37 38 39 40]
 [45 46 47 48]
 [53 54 55 56]
 [61 62 63 64]]


In [71]:
arr = np.arange(1,65).reshape(8,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [85]:
arr = np.array([1,10,100])
np.hstack([arr]*5)

array([  1,  10, 100,   1,  10, 100,   1,  10, 100,   1,  10, 100,   1,
        10, 100])

In [86]:
arr = np.arange(1,61)
np.split(arr,4)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]),
 array([46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])]

In [89]:
arr = np.random.rand(12)*(100-20) + 20
arr

array([72.53976696, 24.0236486 , 32.41266145, 84.1313071 , 86.34749971,
       84.69975739, 46.71355609, 50.09853285, 54.2297035 , 23.06323432,
       68.05583287, 56.78687971])

In [90]:
np.round(arr,3)

array([72.54 , 24.024, 32.413, 84.131, 86.347, 84.7  , 46.714, 50.099,
       54.23 , 23.063, 68.056, 56.787])

In [91]:
arr = np.random.randint(10,100,(7,7))
arr

array([[14, 59, 12, 10, 44, 90, 90],
       [29, 86, 79, 26, 31, 95, 89],
       [52, 80, 95, 88, 28, 37, 63],
       [39, 73, 70, 94, 23, 63, 63],
       [85, 49, 38, 88, 75, 96, 21],
       [51, 40, 24, 33, 12, 62, 80],
       [67, 42, 82, 56, 53, 12, 54]], dtype=int32)

In [96]:
print(np.diag(arr).sum())

480


In [97]:
arr = np.random.randint(1,6,25)
arr

array([1, 5, 1, 4, 1, 2, 2, 1, 3, 2, 2, 2, 1, 2, 5, 1, 5, 1, 1, 1, 2, 4,
       5, 4, 3], dtype=int32)

In [98]:
values, count = np.unique(arr, return_counts=True)
print(values)
print(count)

[1 2 3 4 5]
[9 7 2 3 4]


In [100]:
arr = np.arange(0,20)
arr[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [101]:
arr = np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
print(arr[:,1:2])
print(arr[:,3:4])

[[ 1]
 [ 6]
 [11]
 [16]
 [21]]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]]


In [107]:
arr = np.arange(1,25).reshape(6,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [110]:
print(arr[:3,:])
print(arr[-2:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[17 18 19 20]
 [21 22 23 24]]


In [111]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [115]:
arr = np.arange(1,19)
arr[2::3]

array([ 3,  6,  9, 12, 15, 18])

In [120]:
arr = np.arange(1,26).reshape(5,5)

indices = np.arange(0,5)

diag = arr[indices,indices]
diag

array([ 1,  7, 13, 19, 25])

In [121]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [122]:
mat[0,4] = -1
mat[0,0] = -1
mat[4,0] = -1
mat[4,4] =-1
mat

array([[-1,  2,  3,  4, -1],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [-1, 22, 23, 24, -1]])

In [123]:
arr = np.random.randint(1,50,20)
avg = arr.mean()
arr[arr > avg]

array([32, 35, 31, 24, 29, 23, 47, 29, 37], dtype=int32)

In [125]:
arr = np.random.randint(1,50,(5,6))
arr

array([[29, 43,  8,  9,  2, 38],
       [22,  5, 23, 44, 25, 39],
       [31, 21, 45,  8,  6, 42],
       [48,  7, 42,  9, 34, 42],
       [11, 35,  8, 31, 27, 45]], dtype=int32)

In [126]:
arr[1:4, 2:5]

array([[23, 44, 25],
       [45,  8,  6],
       [42,  9, 34]], dtype=int32)

In [127]:
arr[-1,:] = 0
arr

array([[29, 43,  8,  9,  2, 38],
       [22,  5, 23, 44, 25, 39],
       [31, 21, 45,  8,  6, 42],
       [48,  7, 42,  9, 34, 42],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)